# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- working-segregation

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  tagDate: $[ format('{0:yyyy}.{0:MM}.{0:dd}.{0:HH}.{0:mm}{0:ss}', pipeline.startTime) ]
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  isWorkingSegregation: $[eq(variables['Build.SourceBranch'], 'refs/heads/working-segregation')]

stages:
- stage: Build
  condition: and(succeeded(), eq(variables.isMain, 'true'))
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image and Push
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
              latest
              $(tagDate)
        containerRegistry: DockerHub
        repository: dbcawa/moorings
      env:
        DOCKER_BUILDKIT: 1
    - task: Docker@2
      displayName: Dev Build image and Push
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/dockerdev/Dockerfile'
        tags: |
              moorings_dev_latest
              moorings_dev_$(tagDate)
        containerRegistry: DockerHub
        repository: dbcawa/docker_app_dev
      env:
        DOCKER_BUILDKIT: 1
  - job: BuildWorkingSegregation
    displayName: Build Working Segregation
    condition: and(succeeded(), eq(variables.isWorkingSegregation, 'true'))
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image and Push for Working Segregation
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile.working-segregation'
        tags: |
              working_segregation_latest
              working_segregation_$(tagDate)
        containerRegistry: DockerHub
        repository: dbcawa/working_segregation
      env:
        DOCKER_BUILDKIT: 1
