# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-26 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0129_auto_20190715_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualBookingPeriodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mooring_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooring.MooringAreaGroup')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualBookingPeriodOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('annual_booking_period_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooring.AnnualBookingPeriodGroup')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualBookingPeriodOptionVesselCategoryPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=8, null=True)),
                ('oracle_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('annual_booking_period_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooring.AnnualBookingPeriodOption')),
            ],
        ),
        migrations.CreateModel(
            name='VesselSizeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_size', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('end_size', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('status', models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mooring_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooring.MooringAreaGroup')),
            ],
        ),
        migrations.AlterField(
            model_name='feature',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='annualbookingperiodoptionvesselcategoryprice',
            name='vessel_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooring.VesselSizeCategory'),
        ),
    ]
