# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-08 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0130_auto_20200626_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualbookingperiodoptionvesselcategoryprice',
            old_name='annual_booking_period_group',
            new_name='annual_booking_period_option',
        ),
    ]
