# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-10 06:11
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mooring', '0131_auto_20200708_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAnnualAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateField()),
                ('expiry_dt', models.DateField()),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('booking_type', models.SmallIntegerField(choices=[(0, 'Reception booking'), (1, 'Internet booking'), (2, 'Black booking'), (3, 'Temporary reservation'), (4, 'Cancelled Booking'), (5, 'Changed Booking')], default=0)),
                ('annual_booking_period_group', models.IntegerField(blank=True, null=True)),
                ('cost_total', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('override_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('override_reason_info', models.TextField(blank=True, null=True)),
                ('is_canceled', models.BooleanField(default=False)),
                ('send_invoice', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('cancelation_time', models.DateTimeField(blank=True, null=True)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('override_lines', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('sticker_no', models.TextField(blank=True, null=True)),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canceled_annual_bookings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_annual_booking', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overridden_annual_bookings', to=settings.AUTH_USER_MODEL)),
                ('override_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.DiscountReason')),
            ],
        ),
        migrations.AddField(
            model_name='annualbookingperiodgroup',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualbookingperiodgroup',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
