# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-10 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0132_auto_20200710_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingannualadmission',
            name='expiry_dt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookingannualadmission',
            name='start_dt',
            field=models.DateTimeField(),
        ),
    ]
