# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-24 02:45
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0136_bookingannualadmission_sticker_no_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualbookingperiodgroup',
            name='letter',
            field=models.FileField(blank=True, null=True, upload_to=django.core.files.storage.FileSystemStorage(location='/var/web/moorings/private-media/letters/2020/07/24/10')),
        ),
    ]
