# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-24 03:07
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0137_annualbookingperiodgroup_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualbookingperiodgroup',
            name='letter',
            field=models.FileField(blank=True, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(location='/var/web/moorings/private-media/'), upload_to='letter/%Y/%m/%d/%H'),
        ),
    ]
