# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-24 08:21
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0138_auto_20200724_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionslocation',
            name='annual_admissions_terms',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='annualbookingperiodgroup',
            name='letter',
            field=models.FileField(blank=True, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/var/web/moorings/private-media/'), upload_to='letter/%Y/%m/%d/%H/'),
        ),
    ]
