# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-28 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0140_auto_20200724_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualAdmissionEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('mooring_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooring.MooringAreaGroup')),
            ],
        ),
        migrations.AlterModelOptions(
            name='vesselsizecategory',
            options={'verbose_name_plural': 'Vessel Size Categories'},
        ),
    ]
