# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-28 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0141_auto_20200728_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingannualadmission',
            name='rego_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
