# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-29 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0143_admissionsbooking_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionslocation',
            name='annual_admissions_more_price_info_url',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
