# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-05 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0146_bookingannualadmission_sticker_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingannualadmission',
            name='sticker_created',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
