# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-03 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0148_booking_property_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionslocation',
            name='daily_admissions_more_price_info_url',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='admissionslocation',
            name='daily_admissions_terms',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='admissionslocation',
            name='mooring_booking_terms',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
