# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-10-01 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0150_auto_20200924_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_group', models.SmallIntegerField(choices=[(0, 'Mooring Booking Checks'), (1, 'Annual Admission Booking Checks'), (2, 'Daily Admission Booking Checks')], default=0)),
                ('email', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('mooring_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooring.MooringAreaGroup')),
            ],
        ),
    ]
