# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-11 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0152_auto_20201113_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsbooking',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
