# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-15 06:23
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0154_auto_20210315_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualbookingperiodgroup',
            name='letter',
            field=models.FileField(blank=True, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/moorings/private-media/'), upload_to='letter/%Y/%m/%d/%H/'),
        ),
    ]
