# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-15 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0155_auto_20210315_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='system_id',
        ),
    ]
