# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-23 03:19
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0157_vessellicence'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooringarea',
            name='mooring_specification',
            field=models.SmallIntegerField(choices=[(1, 'Rental Mooring'), (2, 'Private Mooring')], default=1),
        ),
    ]
