# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 04:52
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0158_auto_20210323_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredVesselsMooringLicensing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rego_no', models.CharField(max_length=200)),
                ('vessel_size', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('vessel_draft', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('vessel_beam', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('vessel_weight', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
            ],
            options={
                'verbose_name': 'Registered Vessel (Mooring Licensing)',
                'verbose_name_plural': 'Registered Vessels (Mooring Licensing)',
            },
        ),
    ]
