# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 04:58
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0159_auto_20210329_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredvesselsmooringlicensing',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registeredvesselsmooringlicensing',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
