# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 06:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0160_auto_20210329_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('json_context', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='vessellicence',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='vessellicence',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='registeredvesselsmooringlicensing',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='registeredvesselsmooringlicensing',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
