# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 06:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0161_auto_20210329_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualbookingperiodgroup',
            name='letter',
            field=models.FileField(blank=True, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/projects/moorings/private-media/'), upload_to='letter/%Y/%m/%d/%H/'),
        ),
        migrations.AlterField(
            model_name='updatelog',
            name='json_context',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
