# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0162_auto_20210329_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredvessels',
            name='rego_no',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
