# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-28 02:43
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0163_auto_20210329_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualbookingperiodgroup',
            name='letter',
            field=models.FileField(blank=True, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/projects/moorings-xzzy/private-media/'), upload_to='letter/%Y/%m/%d/%H/'),
        ),
        migrations.AlterField(
            model_name='mooringareastayhistory',
            name='mooringarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_history', to='mooring.MooringArea'),
        ),
        migrations.AlterField(
            model_name='mooringsite',
            name='mooringarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campsites', to='mooring.MooringArea'),
        ),
        migrations.AlterField(
            model_name='mooringsitestayhistory',
            name='campsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_history', to='mooring.Mooringsite'),
        ),
        migrations.AlterField(
            model_name='refundfailed',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RefundFailed_completed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
