# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-28 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0164_auto_20220928_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mooringsitebookingrange',
            name='campsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_ranges', to='mooring.Mooringsite'),
        ),
    ]
