# Generated by Django 5.2.2 on 2025-07-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0167_auto_20241004_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionsbooking',
            name='canceled_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admissionsbooking',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admissionsbooking',
            name='customer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
