# Generated by Django 5.2.2 on 2025-07-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0168_alter_admissionsbooking_canceled_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissionsbooking',
            old_name='canceled_by',
            new_name='canceled_by_id',
        ),
        migrations.RenameField(
            model_name='admissionsbooking',
            old_name='created_by',
            new_name='created_by_id',
        ),
        migrations.RenameField(
            model_name='admissionsbooking',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
