# Generated by Django 5.2.4 on 2025-07-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0169_rename_canceled_by_admissionsbooking_canceled_by_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingannualadmission',
            name='canceled_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingannualadmission',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingannualadmission',
            name='customer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingannualadmission',
            name='overridden_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
