# Generated by Django 5.2.4 on 2025-07-30 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0170_alter_bookingannualadmission_canceled_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingannualadmission',
            old_name='canceled_by',
            new_name='canceled_by_id',
        ),
        migrations.RenameField(
            model_name='bookingannualadmission',
            old_name='created_by',
            new_name='created_by_id',
        ),
        migrations.RenameField(
            model_name='bookingannualadmission',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='bookingannualadmission',
            old_name='overridden_by',
            new_name='overridden_by_id',
        ),
    ]
