# Generated by Django 5.2.15 on 2026-07-06 02:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0171_rename_canceled_by_bookingannualadmission_canceled_by_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='mooringarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mooring.mooringarea', verbose_name='mooring'),
        ),
        migrations.AlterField(
            model_name='mooringarea',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marineparks', to='mooring.marinepark', verbose_name='marine park'),
        ),
        migrations.AlterField(
            model_name='mooringareabookingrange',
            name='campground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_ranges', to='mooring.mooringarea', verbose_name='mooring'),
        ),
        migrations.AlterField(
            model_name='mooringareagroupmember',
            name='emailuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mooringareagroupmember',
            name='mooringareagroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooring.mooringareagroup'),
        ),
        migrations.AlterField(
            model_name='mooringareastayhistory',
            name='mooringarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_history', to='mooring.mooringarea', verbose_name='mooring'),
        ),
        migrations.AlterField(
            model_name='mooringsite',
            name='mooringarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campsites', to='mooring.mooringarea', verbose_name='mooring'),
        ),
        migrations.AlterField(
            model_name='mooringsitebooking',
            name='campsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mooring.mooringsite', verbose_name='mooring site'),
        ),
        migrations.AlterField(
            model_name='mooringsitebooking',
            name='from_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_from'),
        ),
        migrations.AlterField(
            model_name='mooringsitebooking',
            name='to_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_to'),
        ),
        migrations.AlterField(
            model_name='mooringsitebookingrange',
            name='campsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_ranges', to='mooring.mooringsite', verbose_name='mooring site'),
        ),
        migrations.AlterField(
            model_name='mooringsiterate',
            name='campsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='mooring.mooringsite', verbose_name='mooring site'),
        ),
        migrations.AlterField(
            model_name='mooringsiteratelog',
            name='mooringarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marinearea', to='mooring.mooringarea', verbose_name='mooring'),
        ),
        migrations.AlterField(
            model_name='mooringsitestayhistory',
            name='campsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_history', to='mooring.mooringsite', verbose_name='mooring site'),
        ),
    ]
