# Generated by Django 5.2.16 on 2026-07-27 05:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0173_booking_uuid_backfill_and_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsbooking',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
